### ISSUE TITLE
Key Error 'financials'

### ISSUE THREAD

**Issue by ZhuangyingXu** [leonarduschen/pyfinmod#6]
Thanks for the wonderful project, I tried the following lines but it seems like not working:
```
from pyfinmod.financials import Financials
from pyfinmod.ev import enterprise_value
parser = Financials("AAPL")
enterprise_value(parser.balance_sheet_statement)
```

The error I got:
```
Traceback (most recent call last):
  File "c:/GitHub/stock/Discounted_Cash_Flow.py", line 4, in <module>
    enterprise_value(parser.balance_sheet_statement)
  File "C:\Users\zhuaxu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyfinmod\financials.py", line 54, in __getattr__
    json_data = self._fetch_json(item)["financials"]
KeyError: 'financials'
```

I am suspecting it might be some API endpoint error?

**Comment by leonarduschen** [comment]
Hi @ZhuangyingXu thanks for this.

It is indeed an API endpoint error. I've fixed the issue, feel free to reinstall the package :)
